### ISSUE TITLE
Lexer emits EOF on nil slices

### ISSUE THREAD

**Issue by connor4312** [mailru/easyjson#101]
Documentation states that all parsing errors should be LexerErrors, but it's [possible](https://github.com/mailru/easyjson/blob/99e922cf9de1bc0ab38310c277cff32c2147e747/jlexer/lexer.go#L156) for this not to be the case. This resulted in an error incorrectly being flagged as an internal error, when actually the client had simply omitted a field to be parsed.

**Comment by GoWebProd** [comment]
Hello, thank you, but I can't find where says that all parsing errors should be LexerErrors
