### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by erikdubbelboer** [mailru/easyjson#102]
I have [3](https://github.com/mailru/easyjson/pull/99) [pull](https://github.com/mailru/easyjson/pull/77) [requests](https://github.com/mailru/easyjson/pull/78) open that haven't even been looked at in months.

If you are not planning on maintaining this anymore, maybe add someone else who can maintain it?

**Comment by rvasily** [comment]
Victor currently very busy and unavailible for PR
We try to find time at this week and merge your PR

**Comment by erikdubbelboer** [comment]
Thanks.
