### ISSUE TITLE
Relatively loose json type, numeric and string are compatible with each other

### ISSUE THREAD

**Issue by thinkeridea** [mailru/easyjson#111]
Migration from other languages to golang, can much some weakly typed languages even the Java string and numerical mutual compatibility and conversion, lead to the client without a fully the same json type, add a function in the generated code optional loose type model, used for compatibility problems left over by history

**Comment by rvasily** [comment]
I merged recently support for json.Number in #145 
Support for stdlib interface is better solution, i think
