### ISSUE TITLE
Unmarshalling not as fast as expected?

### ISSUE THREAD

**Issue by antholord** [mailru/easyjson#113]
Comparing easyjson to encoding/json, I am not seeing much speed improvements.

I am using easyjson.UnmarshalFromReader to Unmarshall ~2000 objects per second and am noticing an average of 380ms per 2k objects. Using the same test on the same data, I am seeing an average of 420ms per 2k objects with encoding/json.

Are there some optimisation possibilities that I am missing or is this expected behavior?

**Comment by rvasily** [comment]
Can you provide more detailed example with code?

**Comment by antholord** [comment]
Code isnt on github yet but I might ping you guys later when it's available and I have solid test data to prove my point. Didn't mean to come in here to bash you guys, I was mostly wondering if there were some settings to change like pool size, when unmarshalling about 1mb/s of text.

**Comment by rvasily** [comment]
Closed due to lack of detail
