### ISSUE TITLE
support non empty interface

### ISSUE THREAD

**Issue by sreekanth-cb** [mailru/easyjson#121]
easyjson doesn't support non empty interface members during marshal/unmarshal operations where as standard Go encoding/json does.

**Comment by rvasily** [comment]
Can you provide sample code?

**Comment by sreekanth-cb** [comment]
type MyInterface interface {
        Hello() string
}

type MyString string

func (ms MyString) Hello() string {
        return string(ms)
}

type TestObject struct {
                Field MyInterface
 }

**Comment by mkabischev** [comment]
It is impossible to do it without reflection, so I think the only way is to generate code that will run default (reflection-based) marshaller for this field.

**Comment by rvasily** [comment]
I think it possible to have just a little bit of reflection overhead in stdlib marshaler if MyString will have generaded marshallers with easyjson ( implements json.Marshaler interface )

**Comment by deusnefum** [comment]
My preference would be if easyjson doesn't support something (such as a non-empty interface) fallback on the standard json.Marshal. There could be a switch to enable this behavior and the default can be off (for backwards compatibility sake).

**Comment by dgoodine** [comment]
@GoWebProd Why was this closed? I think @deusnefum's suggestion is not unreasonable.

**Comment by dgoodine** [comment]
It should also be noted that the error generated by easyjson give absolutely no context as to where the error occurred in the source file.

**Comment by GoWebProd** [comment]
@dgoodine Hello, issue closed because easyjson not supports non-empty interfaces due to the lack of the ability to use reflect lib. If you want to use interface in struct, please set type to `interface{}` (empty interface)

**Comment by dgoodine** [comment]
Why can't easyjson use the reflect lib?

**Comment by GoWebProd** [comment]
The task of easyjson is parsing and serialization quickly. Reflect does not allow this.
