### ISSUE TITLE
easyjson parser package has issues on Windows

### ISSUE THREAD

**Issue by dnfield** [mailru/easyjson#129]
**Issue 1**: if your %GOPATH% is not matched by case with the way the file system reports the directory, easyjson incorrectly believes that a file that is in %GOPATH% is not.  e.g.:

%GOPATH% = c:\ **u** sers\dnfield\Go
Directory = c:\ **U** sers\dnfield\Go

On Windows, those are the same, and the calling program may or may not use the same convention as what's found in GOPATH.

**Issue 2**: path.IsAbs returns false on Windows for paths that are absolute.  Use filepath.IsAbs instead.

I'm about to create a PR with fixes for these...

**Comment by rvasily** [comment]
Merged
Thanks for report
