### ISSUE TITLE
gopath issue

### ISSUE THREAD

**Issue by geraldstanje** [mailru/easyjson#133]
Hi,

How to fix this issue?

```
geri$ echo $GOPATH
/Users/geri/Desktop/work
geri$ easyjson -all test_obj.go
Error parsing test_obj.go: file '/Users/geri/Desktop/work/test_obj.go' is not in GOPATH
```

**Comment by rvasily** [comment]
It must be like this
`
/Users/geri/Desktop/work
 ├───bin
 ├───pkg
 └───src
`
with all your sources located in `src`
 `src/github.com/mailru/easyjson`  after `go get -u` for easyjson

so, you file must be located at `/Users/geri/Desktop/work/src/test_obj.go`
