### ISSUE TITLE
Invalid JSON generated for NaN and Inf

### ISSUE THREAD

**Issue by dmac** [mailru/easyjson#134]
Package json returns an error if it hits NaN or Inf, but easyjson generates invalid JSON:

main.go:

```go
package main

import (
	"fmt"
	"math"

	"github.com/mailru/easyjson"
)

type T struct {
	F float64
}

func main() {
	t := T{F: math.NaN()}
	b, err := easyjson.Marshal(t)
	if err != nil {
		fmt.Println(err)
		return
	}
	fmt.Println(string(b))
	if err := easyjson.Unmarshal(b, &t); err != nil {
		fmt.Println(err)
		return
	}
	fmt.Println(t)
}
```

Shell:

```
$ easyjson -pkg -all
$ go build -o main && ./main
{"F":NaN}
parse error: syntax error near offset 5 of '{"F":NaN}'
```

**Comment by tobgu** [comment]
Feeding the above JSON to the Python stdlib json parser will actually produce a NaN float. Golang seems to be a bit pickier: https://github.com/golang/go/issues/3480

I would prefer to see some kind of option for floats to control how NaNs are encoded and decoded. For my particular current use case I would like to decode `null` as NaN and encode `NaN` to null.

**Comment by dmac** [comment]
I believe this is still an issue on the latest master: easyjson will produce invalid JSON for NaN or infinity floats. Would it be possible to have this issue reopened?

Since there is not a standard way to encode these values in JSON, I think easyjson should by default return an error when it encounters them, same as standard library json package.
