### ISSUE TITLE
Marshalling functions target struct by value, not reference

### ISSUE THREAD

**Issue by chipdude** [mailru/easyjson#142]
In e.g.
```
func (v MyType) MarshalJSON() ([]byte, error) {
```
the body of MyType is copied in the call... which serves no purpose and is quite expensive when MyType is large.  Please just change to `(v *MyType)` and insert `*` where needed in function body.

**Comment by rvasily** [comment]
Yes, this should be fixed
In next few weeks try to find tine for it

**Comment by rvasily** [comment]
https://play.golang.org/p/xzunZxBnQT
```
package main

import (
	"encoding/json"
	"fmt"
)

type MyType struct {
	Value int
}

func (my *MyType) MarshalJSON() ([]byte, error) {
	fmt.Println("called MarshalJSON on", my)
	return []byte("11111111111111111"), nil
}

func main() {
	// non ref
	val1 := MyType{1}
	data1, _ := json.Marshal(val1)
	fmt.Println(string(data1))

	// ref
	val2 := &MyType{2}
	data2, _ := json.Marshal(val2)
	fmt.Println(string(data2))
}
```
this example demonstrates that pointer method wont work on not ref struct
so, pointer method wont satisfy json.Marshaller on non-ref struct variable
