### ISSUE TITLE
nested struct json encode result is wrong

### ISSUE THREAD

**Issue by zplzpl** [mailru/easyjson#146]
struct:

type TestResponse struct {
    Pagination  `json:"pagination"`
}

type Pagination struct {
	Current struct {
		Page   uint32 `json:"page"`
		Limit  uint32 `json:"limit"`
		Offset uint32 `json:"offset"`
	} `json:"current"`
	Total int64 `json:"total"`
}

code:

xx,_:=xResponse.MarshalJSON()
fmt.Println(string(xx))

result:

{
	"current": {
		"page": 1,
		"limit": 36,
		"offset": 0
	},
	"total": 3039,
}

**Comment by GoWebProd** [comment]
Sorry but I don't understand your problem, can you describe?
If you write

```
type TestResponse struct {
    Pagination Pagination json:"pagination"
}
```

I think you receive what you want.
