### ISSUE TITLE
Refuses to Generate If *Any* Map in Package Has Unsupported Key Type

### ISSUE THREAD

**Issue by tomdeering-wf** [mailru/easyjson#148]
When using easyjson 4d347d79dea0067c945f374f990601decb08abb5 to generate code for a source file, it will refuse to generate code for annotated structs if _any_ struct in the package has unsupported map key types. Example error:

```
map type common.Target not supported: only string and integer keys are allowed
```

This happens even if the "problem" struct is not annotated with `//easyjson:json` or pulled in transitively by one that is.

**Comment by rvasily** [comment]
Problem begins after 4d347d7 or it just version, that you using ?

**Comment by rvasily** [comment]
Can you provide code sample ? It will help in the investigation

**Comment by tomdeering-wf** [comment]
Will provide a code sample. Problem manifested with an earlier version as well, but I tried again with the tip of master (4d347d7) to make sure it wasn't subsequently fixed.

**Comment by tomdeering-wf** [comment]
Woohoo, looking into this further, I found that I really was transitively pulling in something whose map key was of type `common.Target`. Sorry for the false alarm!
