### ISSUE TITLE
Варнинги при инсталяции на 32-битных OS

### ISSUE THREAD

**Issue by MichaelMonashev** [mailru/easyjson#149]
C:\Temp>go get -u -v github.com/mailru/easyjson/...
github.com/mailru/easyjson (download)
github.com/mailru/easyjson/buffer
github.com/mailru/easyjson/jlexer
github.com/mailru/easyjson/jwriter
github.com/mailru/easyjson/benchmark
# github.com/mailru/easyjson/benchmark
C:\dev\src\github.com\mailru\easyjson\benchmark\data_var.go:7: constant 250126199840518145 overflows int
C:\dev\src\github.com\mailru\easyjson\benchmark\data_var.go:12: constant 24012619984051000 overflows int
github.com/mailru/easyjson/bootstrap
github.com/mailru/easyjson
github.com/mailru/easyjson/parser
github.com/mailru/easyjson/gen
github.com/mailru/easyjson/opt
github.com/mailru/easyjson/tests
github.com/mailru/easyjson/easyjson
# github.com/mailru/easyjson/tests
C:\dev\src\github.com\mailru\easyjson\tests\data.go:92: constant 4294967295 overflows int
C:\dev\src\github.com\mailru\easyjson\tests\data.go:95: constant 4294967295 overflows int
C:\dev\src\github.com\mailru\easyjson\tests\data.go:104: constant 4294967295 overflows int
C:\dev\src\github.com\mailru\easyjson\tests\data.go:107: constant 4294967295 overflows int
C:\dev\src\github.com\mailru\easyjson\tests\data.go:195: constant 4294967295 overflows int
C:\dev\src\github.com\mailru\easyjson\tests\data.go:198: constant 4294967295 overflows int

C:\dev\src\github.com\mailru\easyjson\benchmark>go test .
# github.com/mailru/easyjson/benchmark
.\data_var.go:7: constant 250126199840518145 overflows int
.\data_var.go:12: constant 24012619984051000 overflows int
FAIL    github.com/mailru/easyjson/benchmark [build failed]

**Comment by rvasily** [comment]
Замерджил #150 
Сейчас должно быть всё нормально
Прошу проверить

**Comment by MichaelMonashev** [comment]
Сейчас заработало:
```
C:\xxx\src\github.com\mailru\easyjson\benchmark>go test -v -benchmem -benchtime="2s" -bench="."
=== RUN   TestToSuppressNoTestsWarning
--- PASS: TestToSuppressNoTestsWarning (0.00s)
BenchmarkStd_Unmarshal_M-2                  5000            545600 ns/op          23.87 MB/s        7088 B/op        217 allocs/
BenchmarkStd_Unmarshal_S-2                500000              6716 ns/op          12.21 MB/s         400 B/op         13 allocs/
BenchmarkStd_Marshal_M-2                   20000            134500 ns/op          66.52 MB/s       21704 B/op          9 allocs/
BenchmarkStd_Marshal_L-2                     500           6540000 ns/op          68.41 MB/s     1217048 B/op         15 allocs/
BenchmarkStd_Marshal_M_Parallel-2          30000             70733 ns/op         126.49 MB/s       21704 B/op          9 allocs/
BenchmarkStd_Marshal_L_Parallel-2           1000           3589000 ns/op         124.66 MB/s     1217048 B/op         15 allocs/
BenchmarkStd_Marshal_S-2                 1000000              2502 ns/op          32.37 MB/s         312 B/op          3 allocs/
BenchmarkStd_Marshal_S_Parallel-2        2000000              1322 ns/op          61.27 MB/s         312 B/op          3 allocs/
BenchmarkStd_Marshal_M_ToWriter-2          20000            120000 ns/op               9 B/op          1 allocs/op
PASS
ok      github.com/mailru/easyjson/benchmark    28.623s
```

Но почему есть бенчмарки только "Std", т.е. только для encoding/json , а для github.com/mailru/easyjson их нет?
