### ISSUE TITLE
case-insensitive import collision

### ISSUE THREAD

**Issue by veqryn** [mailru/easyjson#182]
Unfortunately my company's github organization has some capital letters in it (such as `MyCompany`).

This causes easyjson to fail any time I try to use it:
```
$ ~/workspace/go/src/github.com/MyCompany/ecm$ easyjson --all ./services/xxxxx/models.go
package main: case-insensitive import collision: "github.com/MyCompany/xxxxxx/services/xxxxx" and "github.com/mycompany/xxxxx/services/xxxxx"
Bootstrap failed: exit status 1
```

I can not change my company's github organization name (sadly).

**Comment by veqryn** [comment]
Probably worth noting that I am on Windows 10.  I haven't done anything weird or funny with my system.

**Comment by rvasily** [comment]
#154 merged
please, check that bug resolved

**Comment by veqryn** [comment]
Works now, Thanks!
