### ISSUE TITLE
easyjson does not respect setting escape-html to false

### ISSUE THREAD

**Issue by veqryn** [mailru/easyjson#183]
```go
type Stuff struct {
	Thing string
}
v := &Stuff{Thing: `hello <&,.='"'=.,&> world`}

buffer := &bytes.Buffer{}
encoder := json.NewEncoder(buffer)
encoder.SetEscapeHTML(false)
_ = encoder.Encode(v)
```

The above will give the correct `{"Thing":"hello <&,.='\"'=.,&> world"}` when not using easyjson.
With easyjson, you get: `{"Thing":"hello \u003c\u0026,.='\"'=.,\u0026\u003e world"}`

**Comment by shmel1k** [comment]
You can try to do something like 
```go
type UnescapableString string

func (s *UnescapableString) MarshalJSON() ([]byte, error) {
 // here you don't escape your string or smth like that
}
```

**Comment by veqryn** [comment]
I am fairly certain that the json package will still escape it after the fact. In any case, it is not feasible to change all my strings to this.

**Comment by shmel1k** [comment]
Sorry for the late answer

Did you try to use jwriter? jwriter has option 'NoEscapeHTML' you could try to use.

**Comment by veqryn** [comment]
I have not. That might be what I need.

**Comment by shmel1k** [comment]
Hello!
Does my suggestion work? If does, can you close the issue, please? :)

**Comment by veqryn** [comment]
Looks like jwriter works.

If possible, it would be great if you could make json.Encoder work too.

**Comment by shmel1k** [comment]
Unfortunately, we can not work with json.Encoder now 😢

**Comment by veqryn** [comment]
Ok. Feel free to close this or keep it open in case you can support it in the future.

**Comment by shmel1k** [comment]
@rvasily close, please :)
