### ISSUE TITLE
How do I handle dynamic fields?

### ISSUE THREAD

**Issue by fiws** [mailru/easyjson#192]
I have a field called `foo` that can be either int or string.
`[{ foo: 123 }, { foo: '123.0' }]`

I know that format is stupid, but it's not my choice..

I would always like an int. What's the easiest way to archive that?

**Comment by rvasily** [comment]
For numbers you can user json.Number as field type
https://golang.org/pkg/encoding/json/#Number
json.RawMessage also useful in some cases - you can later unmarshal it fast it you know type.
And empty interface is you last option.

**Comment by fiws** [comment]
@rvasily thanks. My implementation now looks like this:

```go
type DownloadCount uint32

func (d *DownloadCount) UnmarshalEasyJSON(l *jlexer.Lexer) {
	numString := l.JsonNumber().String()
	num, _ := strconv.ParseFloat(numString, 64)
	*d = DownloadCount(uint32(num))
}

// Uint32 is a helper that returns as uint32
func (d *DownloadCount) Uint32() uint32 {
	return uint32(*d)
}

// [..] using DownloadCount somewhere in my struct [...]
```

Do you think is a valid / "nice" approach? (I'm a total go noob, that's why i would like your feedback)

**Comment by rvasily** [comment]
```
num, err  := l.JsonNumber().Float64()
```
This is better.
And dont ignore errors

**Comment by fiws** [comment]
Thanks. In this case I would like it to just fallback to 0 in case of errors :)
