### ISSUE TITLE
Someting Error occurred when i use easyjson.

### ISSUE THREAD

**Issue by MolenZhang** [mailru/easyjson#195]
Hi:
   I use easyjson to generate my code,but there occurred some error which like this:
$ easyjson -all callback.go
callback_easyjson.go.tmp:1:1: expected 'package', found 'EOF'
Bootstrap failed: exit status 2
  Just give me some advice,please.
Best wishes~

**Comment by cainiaofei** [comment]
Hi, I meet some trouble alike, how you deal with this problem.
