### ISSUE TITLE
easyjson generate cycle import

### ISSUE THREAD

**Issue by registerAutumn** [mailru/easyjson#198]
I try to update via `go get -u github.com/mailru/easyjson` , response error like below
```
import cycle not allowed
package github.com/mailru/easyjson
        imports github.com/mailru/easyjson/jlexer
        imports encoding/json
        imports fmt
        imports os
        imports internal/poll
        imports time
        imports time
```
go version `go version go1.11.2 windows/amd64`

**Comment by shmel1k** [comment]
Hello
Have just tried it with go1.11.1 linux/amd64 and it worked correct.
Can you send your 'go env', please?
