### ISSUE TITLE
Unmarshal fixed size array of different type

### ISSUE THREAD

**Issue by ReenExe** [mailru/easyjson#199]
Exists structure like
```json
[
    [1, 2, "s"],
    [1.01, 2, "b"],
    [1.02, 2, "s"]
]
```
can any tags in easyjson lib or other to can unmarshal to
```go
type Orderbook struct {
	Price    float64 `json:"0,index"`
	Quantity float64 `json:"1,index"`
	Side     string  `json:"2,index"`
}

//easyjson:json
type OrderbookSlice []Orderbook
```

already read https://godoc.org/encoding/json#Marshal
```text
...
- integer keys are converted to strings
...
```

**Comment by ReenExe** [comment]
Some play:
```go
// main.go
package main

import "fmt"

type Orderbook struct {
	Price    float64 `json:"0"`
	Quantity float64 `json:"1"`
	Side     string  `json:"2"`
}

//easyjson:json
type OrderbookSlice []Orderbook

func main() {
	content := `
[
    [1, 2, "s"],
    [1.01, 2, "b"],
    [1.02, 2, "s"]
]
	`

	var result OrderbookSlice

	result.UnmarshalJSON([]byte(content))

	fmt.Printf("%+v\n", result)
}
```

```bash
easyjson -all main.go 
go run *
// Output: "[{Price:0 Quantity:0 Side:}]"
```

**Comment by shmel1k** [comment]
No. Lexer can not understand such kind of structures. If you take a look at generated code, you can make sure that lexer waits for the next closing `]` bracket.  If you had not ignored errors, you would have seen the error like `, parse error: expected { near offset 5 of ''`

So I am not sure that it looks like a bug.

**Comment by rvasily** [comment]
Afaik there is no libs with these feature.
You can only manually white code, based on easyjson, to unpack slices in struct.

**Comment by ReenExe** [comment]
Такой сжатый формат сейчас часто встречаю в WebSocket ответах
```json
[
    [1, 2, "s"],
    [1.01, 2, "b"],
    [1.02, 2, "s"]
]
```
и думал что в проектах Mail.Ru подобное есть

@shmel1k, я пропустил в заголовке указать что это *предложение*
@rvasily, спасибо, тепер буду знать что такие библиотеки в Go еще отсутствуют
