### ISSUE TITLE
Generates a code go staticcheck linter swears at (&*x)

### ISSUE THREAD

**Issue by dkolistratova** [mailru/easyjson#207]
golang staticckeck says: 
 &*x will be simplified to x. It will not copy x.

I have a struct with pointers in fields:
type Type1 struct {
	...
	From       *Type2 `json:"from,omitempty"`
	Through    *Type2 `json:"through,omitempty"`
	...
}

it generates:
	case "from":
              ...
             easyjson...decode..(in, &*out.From)

I want to check my code with linters, but have to ignore this one

**Comment by shmel1k** [comment]
Hello
https://github.com/mailru/easyjson/pull/209
You can take code from here in order not to wait for MR to be merged.

**Comment by rvasily** [comment]
#209 merged
