### ISSUE TITLE
add a flag to serialize int64 as string ?

### ISSUE THREAD

**Issue by Michael2008S** [mailru/easyjson#210]
Becase some browser can't handle a full 64bit value as a number, so the only way to ensure they can work for those clients is to handle them as strings.

So Can it add a flag like '--int64_to_string' to convert  'int64'/'time.Duration'  as ’string‘ type  in json .

The protobuf was process json like this：
https://developers.google.com/protocol-buffers/docs/proto3#json

int64, fixed64, uint64 | string | "1", "-10" | JSON value will be a decimal string. Either numbers or strings are accepted.
-- | -- | -- | --

**Comment by shmel1k** [comment]
```go

**Comment by Michael2008S** [comment]
Hi @shmel1k .
When I use 
```go
type A struct {
	// timeout of this backend
	Timeout time.Duration `json:",string"`
}
```
to generate the code.

It generate:
```go
out.Int64Str(int64(in.Timeout))
```
And the MarshalJSON result It's ：

```json
{
"timeout": "3000000000"
}
```

But I need the to MarshalJSON like this:

```json
{
"timeout": "3s"
}
```

with the go code
```go
out.String(in.Timeout.String())
```

**Comment by shmel1k** [comment]
https://play.golang.org/p/s3OvljK7Ajf

I do not think that 3s is a valid JSON RFC value. https://tools.ietf.org/html/rfc7159

**Comment by Michael2008S** [comment]
I try to  regenerate the config file :
https://github.com/devopsfaith/krakend-ce/blob/master/krakend.json

```go
{
    "version": 2,
    "name": "My lovely gateway",
    "port": 8000,
    "cache_ttl": "3600s",
    "timeout": "3s",
```
Which  was use this format .

But  It use `mapstructure` not json format:

```go 
// ServiceConfig defines the krakend service
type ServiceConfig struct {
	// name of the service
	Name string `mapstructure:"name"`
	// set of endpoint definitions
	Endpoints []*EndpointConfig `mapstructure:"endpoints"`
	// defafult timeout
	Timeout time.Duration `mapstructure:"timeout"`
	// default TTL for GET
	CacheTTL time.Duration `mapstructure:"cache_ttl"`
```

**Comment by shmel1k** [comment]
Dont see anything connected with `json`
See only something like 'mapstructure'
I think you should go https://github.com/devopsfaith/krakend/blob/master/config/parser.go and find all the answers youre looking for

**Comment by Michael2008S** [comment]
@shmel1k  Thanks
