### ISSUE TITLE
Marshal custom map keys

### ISSUE THREAD

**Issue by LepikovStan** [mailru/easyjson#212]
Hi, if I try to marshal struct like this

`type Flag int`
`m := map[Flag]bool`
`easyjson.Marshal(&m)`

map key of type Flag convert to integer in string, but if it implement TextMarshaler interface standart library convert it to string value returns from MarshalText method, would be nice to maintain this behavoir

**Comment by shmel1k** [comment]
Looks like you're russian
Напиши по-русски, не очень понятно, что ты хочешь :)

**Comment by LepikovStan** [comment]
))) у меня есть мапа с ключами типа Flag int который enum (iota, все дела), если я такую мапу маршалю в json, то ключи маршалятся как строки с числами {"1":"..."}, в стандартной либе если у моего типа Flag есть MarshalText метод - то ключ маршалится с помощью этого метода в нормальную строку, которую я описываю в этом методе, например 1->"one", а не "1", тут не нашел как это сделать автоматически, проблему решил только тем что залез в сгенерированный код и там напрямую поменял способ маршалинга этих полей, но в сгенерированный код не очень хочется лезть, если есть возможность это автоматизировать было бы неплохо. Проблема ещё описана тут например https://stackoverflow.com/questions/52161555/how-to-custom-marshal-map-keys-in-json

**Comment by shmel1k** [comment]
https://golang.org/pkg/encoding/#TextMarshaler
Ты говоришь об этом, я тебя понял
Ну да, если это актуально, то можно впилить на этапе генерации

**Comment by LepikovStan** [comment]
Да, я говорю об этом, если есть время, то можете сделать. По идее это поддержка стандартного поведения, а не что-то особенное. Спасибо

**Comment by shmel1k** [comment]
а, ок, впилим тогда

**Comment by shmel1k** [comment]
https://github.com/mailru/easyjson/blob/master/gen/encoder.go#L103
https://github.com/mailru/easyjson/blob/master/gen/decoder.go#77

Вообще, тут уже есть этот функционал

**Comment by LepikovStan** [comment]
вот пример
`package main

import (
	"fmt"

	"github.com/mailru/easyjson"
)

const (
	TextFlag Flag = iota
)

type Flag int

func (f Flag) MarshalText() (text []byte, err error) { return []byte("text"), nil }

// easyjson:json
type Flags map[Flag]string

func main() {
	flags := make(Flags)
	flags[TextFlag] = "test"

	r, err := easyjson.Marshal(flags)
	fmt.Println(string(r), err)
}`
результат будет `{"0":"test"}`, а по идее должен быть `{"text":"test"}` и если вместо easyjson тут написать пакет json - то так и будет

**Comment by shmel1k** [comment]
Посмотри, что генерится в MarshalEasyJSON(). Если там генерится какая-то шляпа, то бага

И да, вероятно, проблема из-за того, что должно быть 

```go
func (f *Flag) MarshalText(
```

**Comment by LepikovStan** [comment]
не от пойнтера это на зависит, в сгенерированном файле 
`if in == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
		out.RawString(`null`)
	} else {
		out.RawByte('{')
		v2First := true
		for v2Name, v2Value := range in {
			if v2First {
				v2First = false
			} else {
				out.RawByte(',')
			}
			out.IntStr(int(v2Name))
			out.RawByte(':')
			out.String(string(v2Value))
		}
		out.RawByte('}')
	}`

ключ обрабатывается  функцией IntStr

**Comment by rvasily** [comment]
#219 merged
