### ISSUE TITLE
_test.go files breaks -pkg option

### ISSUE THREAD

**Issue by bobappleyard** [mailru/easyjson#217]
I've got an issue very similar to https://github.com/mailru/easyjson/issues/187

However, in my case the `_test.go` files are declared as being in the same package as the package they are testing.

If the tests define any struct types, this leads to errors like:

    ./lib_easyjson.go:44:41: undefined: testStruct

EDIT: reviewing the code leads me to conclude that the `-pkg` option is only relevant to `go generate`. It appears to handle passing directories as command line options and then searching them for `*.go` files. This could do with documenting in the README.

The problematic part appears to be in `parser/parser.go`, we should be passing a filter to `parse.Dir` to exclude test files.

**Comment by SchumacherFM** [comment]
This is annoying and I hope the guys will merge the PR soon.
