### ISSUE TITLE
interface type error not supported: only interface{} is allowed

### ISSUE THREAD

**Issue by zhangruiskyline** [mailru/easyjson#222]
I have a struct like

type sampleone struct {
	statusCode   int
	responseBody string
	Error        error
}

and error is a built interface

// The error built-in interface type is the conventional interface for
// representing an error condition, with the nil value representing no error.
type error interface {
	Error() string
}

when generate easy_json, there is some issue as "interface type error not supported: only interface{} is allowed"

wonder why it will like this and how do we resolve?

**Comment by shmel1k** [comment]
Yes, only empty and MarshalJSON/MarshalEasyJSON/MarshalText interfaces are allowed in easyjson

**Comment by zhangruiskyline** [comment]
@shmel1k Thanks, in this case, how do we modify our code to meet requirement for easyjson?

**Comment by shmel1k** [comment]
Use empty interfaces instead of some typed interfaces.

We do not use reflection in runtime so we can not support typed interfaces :(

**Comment by rvasily** [comment]
I think we need to fallback to stdlib in case of marshaling.

But we cannot support unmarshalling in interface type, because it does not have fields to access. This fields must be ignored diring codegeneration, with some warning.

PR are welcome

**Comment by tamerh** [comment]
hi, How to skip interface struct while generating?

**Comment by shmel1k** [comment]
`json: «-»`

**Comment by tamerh** [comment]
actually was needed for generated code but i realised i should not skip the interface type thanks anyway.
