### ISSUE TITLE
generate easyjson file error

### ISSUE THREAD

**Issue by tianjialin** [mailru/easyjson#231]

**Comment by tianjialin** [comment]
when i use "easyjson -all ****.go" to generate easyjson file, error appears: 

**union_material_easyjson.go.tmp:1:1: expected 'package', found '['
Bootstrap failed: exit status 2**

**Comment by shmel1k** [comment]
hello
afaik, we do not support regex in file names.
but first, try '*.go', not '****.go'

**Comment by rvasily** [comment]
Pleasem attach output of this command
```
head union_material_easyjson.go.tmp
```
Looks like this is not golang source

**Comment by tianjialin** [comment]
> hello
> afaik, we do not support regex in file names.
> but first, try '_.go', not '_***.go'

my command is "easyjson -all union_material_easyjson.go"

**Comment by tianjialin** [comment]
> Pleasem attach output of this command
> 
> ```
> head union_material_easyjson.go.tmp
> ```
> 
> Looks like this is not golang source

i don't have a file named 'union_material_easyjson.go.tmp';
my union_material_easyjson.go is

> 
> // TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
> // compilable during generation.
> 
> package  model
> 
> import (
>   "github.com/mailru/easyjson/jwriter"
>   "github.com/mailru/easyjson/jlexer"
> )
> 
> func ( UnionMaterialModel ) MarshalJSON() ([]byte, error) { return nil, nil }
> func (* UnionMaterialModel ) UnmarshalJSON([]byte) error { return nil }
> func ( UnionMaterialModel ) MarshalEasyJSON(w *jwriter.Writer) {}
> func (* UnionMaterialModel ) UnmarshalEasyJSON(l *jlexer.Lexer) {}
> 
> type EasyJSON_exporter_UnionMaterialModel *UnionMaterialModel
> 
> func ( UnionMaterialModelStruct ) MarshalJSON() ([]byte, error) { return nil, nil }
> func (* UnionMaterialModelStruct ) UnmarshalJSON([]byte) error { return nil }
> func ( UnionMaterialModelStruct ) MarshalEasyJSON(w *jwriter.Writer) {}
> func (* UnionMaterialModelStruct ) UnmarshalEasyJSON(l *jlexer.Lexer) {}
> 
> type EasyJSON_exporter_UnionMaterialModelStruct *UnionMaterialModelStruct
> 
> func ( UnionTplStruct ) MarshalJSON() ([]byte, error) { return nil, nil }
> func (* UnionTplStruct ) UnmarshalJSON([]byte) error { return nil }
> func ( UnionTplStruct ) MarshalEasyJSON(w *jwriter.Writer) {}
> func (* UnionTplStruct ) UnmarshalEasyJSON(l *jlexer.Lexer) {}
> 
> type EasyJSON_exporter_UnionTplStruct *UnionTplStruct
> 
> func ( VideoInfo ) MarshalJSON() ([]byte, error) { return nil, nil }
> func (* VideoInfo ) UnmarshalJSON([]byte) error { return nil }
> func ( VideoInfo ) MarshalEasyJSON(w *jwriter.Writer) {}
> func (* VideoInfo ) UnmarshalEasyJSON(l *jlexer.Lexer) {}
> 
> type EasyJSON_exporter_VideoInfo *VideoInfo
>

**Comment by tianjialin** [comment]
finally i solve it. it's environment problem. i guass it's idea generate some tmp file affect easyjson.

**Comment by Chandlerblaid** [comment]
I am having the same issue. @tianjialin how did you resolve your environment issue?

**Comment by tianjialin** [comment]
move your file to another path where idea has no project in. Then generate easyjson file again.


| |
公用邮箱
邮箱：tjialin1990@126.com
|

签名由 网易邮箱大师 定制

On 12/23/2019 07:43, Chandler Blaid Burgess wrote:

I am having the same issue. @tianjialin how did you resolve your environment issue?

**Comment by Chandlerblaid** [comment]
awesome, that worked for me. Thanks @tianjialin
