### ISSUE TITLE
电脑重启后，报错：

### ISSUE THREAD

**Issue by ayaya118** [mailru/easyjson#232]
expected 'package', found 配置文件错误

D:\gopath\src\leibe.cn\roomMessageOutput\models\roomMessage>easyjson -all messag
e.go
message_easyjson.go.tmp:1:1: expected 'package', found 配置文件错误
Bootstrap failed: exit status 2

**Comment by rvasily** [comment]
Pleasem attach output of this command
```
head message_easyjson.go.tmp
```
Looks like this is not golang source
