### ISSUE TITLE
can we generate Marshall/Unmarshall for import lib?

### ISSUE THREAD

**Issue by zhangruiskyline** [mailru/easyjson#234]
Let's see in our current code A.go we have import a github lib (B.go) that has lots of json structure, however when running for easyjson to generate json marshaller and unmarshaller for A.go, it dose not generate corresponding json marshaller and unmarshaller for B.go, anyway we can recursively generate? or anyway we should be able to deal with this case like manual generate?

**Comment by shmel1k** [comment]
Looks like you can not
The only this you can is to generate easyjson stub for you library. Or rewrite code in such way, that you 'reimplement' structures from your B library, and use easyjson generator for this rewritten code.

**Comment by shmel1k** [comment]
Looks like you can not
The only this you can is to generate easyjson stub for you library. Or rewrite code in such way, that you 'reimplement' structures from your B library, and use easyjson generator for this rewritten code.

**Comment by zhangruiskyline** [comment]
I think we can define another structure in our application which include the data structure in lib. then easyjson can generate recursive into sub lib. looks working! please let me know whether I am not doing right way
