### ISSUE TITLE
create without in GOPATH

### ISSUE THREAD

**Issue by jinfagang** [mailru/easyjson#241]
```
Error parsing common.go: file '/Volumes/xs/awesome/uranus/chat/picbed/common.go' is not in GOPATH

```

How do I create without in GOPATH?

**Comment by shmel1k** [comment]
unfortunately, you can not create without gopath :(
some kind of specific

**Comment by sinys15** [comment]
Why you are hardcoded 
func getPkgPathFromGOPATH(
...
prefix := **filepath.Join(p, "src")** + string(filepath.Separator)
...
Why I can't set direct path to a file?

**Comment by shmel1k** [comment]
because of GOPATH structure
src/some_package
