### ISSUE TITLE
Is it possible to always parse time.Time as a Unix epoch?

### ISSUE THREAD

**Issue by MichaelSnowden** [mailru/easyjson#259]
I am reading a JSON response with a field t that is a unix epoch in milliseconds. Currently, my approach is to have a private variable in my response that is timestampMs and then a Time() function which does the conversion. I'd prefer if I could just have a Time field in my struct and tell easyjson to parse time.Time using my custom logic. Is this possible?

**Comment by shmel1k** [comment]
You can always implement your own MarshalEasyJSON/UnmarshalEasyJSON functions
