### ISSUE TITLE
file is not in GOPATH

### ISSUE THREAD

**Issue by dgorocho-quest** [mailru/easyjson#261]
GOPATH=C:\Users\dgorocho\Go
file located in C:\Users\dgorocho\Go\Src
running command easyjson -all fast.go produces error "Error parsing fast.go: file 'C:\Users\dgorocho\Go\Src\fast.go' is not in GOPATH"

![image](https://user-images.githubusercontent.com/39267894/69624437-57d00c00-104d-11ea-8922-8fb86f08b741.png)

**Comment by mrVanboy** [comment]
I'm not a windows expert, but shouldn't the `src` directory be lowercased (`C:\Users\dgorocho\Go\Src` vs `C:\Users\dgorocho\Go\src`)?

**Comment by shmel1k** [comment]
@dgorocho-quest try to lowercase the 'src' folder

**Comment by zifter** [comment]
Should be fixed in https://github.com/mailru/easyjson/pull/263
