### ISSUE TITLE
How to generate easyjson files for all project?

### ISSUE THREAD

**Issue by MeshyIce** [mailru/easyjson#262]
Hi.

I would like to use this library for our big codebase at work. The problem is, we have the code split into many directories and running `easyjson -all *.go` for every directory is time-consuming and error-prone.

Is there a way to generate `easyjson.go` files for nested directories as well?

I will note that our projects are split into multiple packages as such:

```
-- main
-- -- package_1
-- -- package_2
-- -- package_3
-- -- -- package_3_1
-- -- -- package_3_2
```

Thanks!

**Comment by MeshyIce** [comment]
Sorry for the problems :)

**Comment by MeshyIce** [comment]
Sorry for re-opening and closing the issue twice :)

**Comment by GoWebProd** [comment]
I think, that you can use command like this:
`find . -maxdepth 1 -type d -printf '%f\n' | sort | uniq | xargs -I {} easyjson "{}"`

**Comment by phxism** [comment]
> I think, that you can use command like this: `find . -maxdepth 1 -type d -printf '%f\n' | sort | uniq | xargs -I {} easyjson "{}"`

ugly solution... so why not consider support for wildcard like *.go or other pattern which saves more time and effort

**Comment by phxism** [comment]
> > I think, that you can use command like this: `find . -maxdepth 1 -type d -printf '%f\n' | sort | uniq | xargs -I {} easyjson "{}"`
> 
> ugly solution... so why not consider support for wildcard like *.go or other pattern which saves more time and effort

add `//go:generate easyjson -all -snake_case $GOFILE` to the file you want go generate,then run `go generate /path/to/your/model`
