### ISSUE TITLE
findStringLen() is about 90% of Unmarshal profile

### ISSUE THREAD

**Issue by kirillx** [mailru/easyjson#264]
findStringLen() is very unoptimal and written in a plain loop. As a result it takes up to 90% of my profiles related to easyjson.

Seems it can be optimised out via:
1. findStringLen() should use asm optimised strings.IndexByte('"') and not perform unescaping (see p.3)
2. fetchString() should also avoid escaping as it is frequently called even for unneeded fields in Skip() -> FetchToken().
3. lexer.String() should perform real escaping when string is needed. It should also scan the string for the second time using string.IndexByte('\') to find the scape sequence.

**Comment by GoWebProd** [comment]
Hello, can you give example of code?

**Comment by kirillx** [comment]
This artificial test case spends about 40% in findStringLen() as per attached profile.
The % is higher the longer the values in non-interested fields are.

[teasyjson.zip](https://github.com/mailru/easyjson/files/4142810/teasyjson.zip)
[profile002.pdf](https://github.com/mailru/easyjson/files/4142815/profile002.pdf)

**Comment by kirillx** [comment]
I suggest to replace findStringLen with smth like:

```
func findStringLen(data []byte) (isValid bool, length int) {
       for {
               idx := bytes.IndexByte(data, '"')
               if idx == -1 {
                       return false, len(data)
               }
               if idx > 0 && data[idx-1] != '\\' {
                       return true, idx
               }
               data = data[idx+1:]
       }
}
```

and perform unescaping where .String() is called.
BTW we can remove 1 allocation for strings requiring unescaping as currently fetchString() performs 1 allocation at:
`       r.token.byteValue = make([]byte, 0, length)`
and later one more allocation in .String() where []byte is converted to string.
