### ISSUE TITLE
Проблема при генерации функций маршалинга/демаршалинга

### ISSUE THREAD

**Issue by SergeyLeo** [mailru/easyjson#277]
Запускаю 
 easyjson -all -no_std_marshalers ./pkg/abbyy/json.go
Получаю:
easyjson-bootstrap507678629.go:12:3: cannot find package "." in:
        /media/common/Projects/go-tools/vendor/github.com/mailru/easyjson/gen
PkgName value = abbyyBootstrap failed: exit status 1
Последняя строка PkgName - это я в код дописал, что бы понять что там за имя пакета он формирует.
Попробовал перейти в папку файла и запустить
easyjson -all -no_std_marshalers json.go
Такая же песня.
Поможете?

**Comment by souz9** [comment]
Hello. I have the same issue.

Looks like it's related to last update of Go 1.14, particularly building behavior for projects with `vendor` folder.

Both of these  actions help me:
1. Removing `vendor` folder in the root of a project, or
2. switching go version in `go.mod`: `go 1.14` -> `go 1.13`.

**Comment by SergeyLeo** [comment]
Thank you very mutch. I will try this magic. :) 
I found [examples](https://github.com/sadlil/experiments/tree/master/go/easyjson)  of how this work. Maybe I will add something myself :)
