### ISSUE TITLE
Unable to unmarshal *int64 string

### ISSUE THREAD

**Issue by cjhubert** [mailru/easyjson#281]
As of #271 it appears that attempting to unmarshal a value into a quoted `*int64` results in an error:

```golang
package et

import (
	"encoding/json"
	"log"
)

//go:generate easyjson -all et.go

type TestStruct struct {
	ID *int64 `json:"id,string"`
}

func Call() {
	j := `{"id":"2"}`
	var foo TestStruct
	err := json.Unmarshal([]byte(j), &foo)
	if err != nil {
		panic(err)
	}
	log.Printf("%d", *foo.ID)
}
```

Output as of f8275962573a1041bacdaf1b016b8056a56b44db
```sh
2020/04/14 16:57:16 2
```

Output as of 67202f78690e94c5ab90743e5ed68840a7372073
```sh
panic: parse error: expected number near offset 9 of '2'

goroutine 1 [running]:
/easytest/src/et.Call()
	/easytest/src/et/et.go:19 +0x129
main.main()
	/easytest/main.go:6 +0x20
exit status 2
```

**Comment by GoWebProd** [comment]
Thank you for report.

Unfortunately, now easyjson can't unpack opt types (like *int64) from string.

**Comment by GoWebProd** [comment]
#271 reverted. Need write tests for opt types and fix.

**Comment by cjhubert** [comment]
Thanks for the quick resolution, I'll close this since the issue has been resolved with the revert
