### ISSUE TITLE
Two easyjson for same struct

### ISSUE THREAD

**Issue by pacoguzman** [mailru/easyjson#283]
Sorry if this is not the place to write the following question.

We have struct which we want to detect unknown fields when unmarshaling from a request payload made from users. But in the other side we want to unmarshal content already on a storage in this case we just one to discard the unknown fields.

Currently we setup two packages that define the same struct and run easyjson with and without `-disallow_unknown_fields` flag.

I would like to know if there is simpler way of doing this, hopefully only defining the struct once.

Thanks in advance.

**Comment by GoWebProd** [comment]
Hello, unfortunately, you can't make this simpler. You need two different decoders and so you need two different structures.

**Comment by pacoguzman** [comment]
Thanks, that what we have right now
