### ISSUE TITLE
Skip some structs during the generation

### ISSUE THREAD

**Issue by ParshinPavel** [mailru/easyjson#288]
Hi,

Is it possible to skip some structs providing them a custom marshalling/umarshalling implementation? For example, using a pragma `//easyjson:skip` or somehow else.

I'd like to generate marshallers to all my structs in a package excluding just several ones and now I have to put a pragma `//easyjson:json` almost for each struct.

**Comment by GoWebProd** [comment]
Hello. No, you can only generate for all structs in file (by running easyjson with flag -all) or for selected structs by `//easyjson:json`. But I think that your idea about `//easyjson:skip` can be realized.

**Comment by ParshinPavel** [comment]
I realized that it seems quite easy to implement this feature. Please, have a look at my PR
