### ISSUE TITLE
easyjson does not generate code in Go 1.15 environment

### ISSUE THREAD

**Issue by martin-sucha** [mailru/easyjson#303]
When running easyjson without `-all` option under Go 1.15, easyjson outputs only `import` and `var` headers, but no JSON (un)marshalling methods. My guess is that something prevents it to see the `//easyjson:json` comments.

To reproduce it should be enough to run `make` with Go 1.15.

**Comment by martin-sucha** [comment]
This is caused because the directives are no longer present in output of `ast.CommentGroup.Text()` since https://github.com/golang/go/commit/5a550b695117f07a4f2454039a4871250cd3ed09. The fix would be to use `ast.CommentGroup.List` directly.

**Comment by GoWebProd** [comment]
Hello, thank you for reporting. Will be fixed in #304

**Comment by GoWebProd** [comment]
Released

**Comment by martin-sucha** [comment]
Thanks!

**Comment by zikaeroh** [comment]
There's something wrong with the 0.7.4 tag, and 0.7.4.1 isn't a valid semver, so Go thinks 0.7.3 is still the latest version. You may want to tag 0.7.5 to make sure that Go knows there's a newer version. See: https://pkg.go.dev/github.com/mailru/easyjson?tab=versions

**Comment by martin-sucha** [comment]
Neither `0.7.4` nor `0.7.4.1` are recognized by Go as the tags don't start with `v` (and as you write, `0.7.4.1` is not valid because the tag needs to have 3 numbers), see [Semantic versions and modules](https://blog.golang.org/publishing-go-modules#TOC_3.). The correct tag to add would be `v0.7.5`.

**Comment by zikaeroh** [comment]
Ah, you're totally right, I completely missed the missing `v`. Tagging `v0.7.4` (or maybe something newer) should work out. For now I've gone and just did `@master` and pulled the fixed commit.

**Comment by GoWebProd** [comment]
You are sure. Fixed. Thanks.

**Comment by seregayoga** [comment]
Hi all! Thank you for fixing this issue. But seems like there is a mistake in tag name `v.0.7.5` and go mod can't correctly upgrade to a newer version. When I run `go get -u -v github.com/mailru/easyjson@v.0.7.5` I see in the go.mod
`github.com/mailru/easyjson v0.7.4-0.20200812114229-8ab5ff9cd8e4`
tag v0.7.4 but points to a latest commit that in github marked as `v.0.7.5`. Seems like go mod doesn't work with tag names with dot after `v`.
