### ISSUE TITLE
tags v.0.7.5 isn't in the expected format

### ISSUE THREAD

**Issue by MStoykov** [mailru/easyjson#305]
I just tried to update the version and was wondering why `go mod` didn't want to get v0.7.5 until I released that there is a dot (`.`) between `v` and `0.7.5` 

I guess you can just retag with `v0.7.5` so `go mod` won't have trouble

**Comment by stefanb** [comment]
cc: @GoWebProd ❗

**Comment by GoWebProd** [comment]
Sorry, fixed.

**Comment by stefanb** [comment]
Tnx, works now!
