### ISSUE TITLE
Streaming reflective JSON encoder

### ISSUE THREAD

**Issue by x4m** [mailru/easyjson#307]
Hi!
I'm coping with OOMs in https://github.com/wal-g/wal-g/issues/738
And looking for good JSON lib so that we could avoid materializing JSON in memory. But the code is shared among many different types of JSON, so I do not want to use precompiled JSON encoder and want reflective one. Is easyjson suitable for this task?

**Comment by GoWebProd** [comment]
Hello, no. easyjson can work only with precompiled structs

**Comment by x4m** [comment]
Thanks!
