### ISSUE TITLE
Unsafe in lexer.go

### ISSUE THREAD

**Issue by tkrajina** [mailru/easyjson#34]
Hi all,

I'm working on an appengine application and one of my dependencies recently added an import to `easyjson/jlexer`. The problem is that https://github.com/mailru/easyjson/blob/master/jlexer/lexer.go#L207 is importing `unsafe` and deploying to appengine fails for code with `unsafe`.

Now, I understand that this is done to prevent copying the string bytes, but is there any way to rewrite it without `unsafe`? It would help all of us who write appengine apps.

Thanks,
tk

**Comment by vstarodub** [comment]
Will a build tag, e.g. 'easyjson_nounsafe', solve your problems? It'll also be somewhat slower, I guess something like 1.5x or less slower for unmarshalling.

**Comment by tkrajina** [comment]
Yes I know that it will be slower but at least it will work (and it is rarely called anyway). Thanks!

**Comment by mpalomas** [comment]
I am also interested in the outcome of this issue, for the same reason: I work on App Engine and my app has an indirect dependency on easyjson, and the usage of unsafe is blocking us.
Would the core contributors consider the usage of conditional compilation so that at least we can build for App Engine (accepting the performance impact)?
Thanks!

**Comment by mindworker** [comment]
I had the same issue with @mpalomas where an indirect dependency in [go-openapi](https://github.com/go-openapi/strfmt) on `easyjson` is causing problems on our App Engine build.

I created a pull request, which introduced two build tags `easyjson_nounsafe` and `appengine` that  disables the use of `unsafe` package and fallbacks to a normal copy-based conversion from []byte to string.

Hope this can be merged!

**Comment by rvasily** [comment]
Merged
