### ISSUE TITLE
map[string]interface{} to json

### ISSUE THREAD

**Issue by KentAVP** [mailru/easyjson#344]
i didn't get how could i use easyjson for converting map[string]interface{} to json, do you have any example? 

ребята, дайте пример как конвертнуть map[string]interface{} в json, я пока совсем не понял как это сделать с вашей либой , но вижу что бенчмарки крутые - она мне нужна :)

**Comment by rvasily** [comment]
easyjson основан на кодогенерации по конкретным структурам. В случае с map[string]interface{} нет понимания что там будет внутри и кодогенерация невозможна, тем более на распаковку, так что профита от него особого не будет.

Стоит или попробовать выделить структуры, или использовать другую библиотеку.
