### ISSUE TITLE
file X is not in GOPATH error when GOPATH ends with `/`

### ISSUE THREAD

**Issue by FZambia** [mailru/easyjson#4]
Hello, here is a problem I came across when trying `easyjson` – when I run `easyjson.go myfile.go` I get an error from title.

After investigating a bit I found the reason: my GOPATH ends with `/` so it does not pass a check in [this](https://github.com/mailru/easyjson/blob/master/parser/parser_unix.go#L21) line.

The easiest fix I can imagine is sth like:

```go
import "path/filepath"
...
prefix := filepath.Join(p, "src") + "/"
```
But maybe there is a cleaner way to do it.

**Comment by vstarodub** [comment]
Thanks for the report! Fixed.
