### ISSUE TITLE
Configurable Marshalling

### ISSUE THREAD

**Issue by tcolar** [mailru/easyjson#40]
Hi, not sure if you would think it's useful/good and would want a PR, but I added a feature to easy-json to allow some manipulation of the Marshaller at runtime.

Use case is that it's not uncommon to have a large struct and sometimes wanting to (dynamically) exclude some fields from marshaling (to send json subset of struct to endpoints)

See here,
https://github.com/tcolar/easyjson/pull/1

**Comment by rvasily** [comment]
easyjson is simple instrument for json (de)serialization
it's main purpose is achive performance by avoid runtime magic

if you dont want to cut some fields from result - you can use opt.* fields
