### ISSUE TITLE
v0.8 and v0.9 are incorrect version format for Go

### ISSUE THREAD

**Issue by suzuki-shunsuke** [mailru/easyjson#406]
I'm sorry if this is intended, but v0.8 and v0.9 are incorrect version format for Go.

https://github.com/mailru/easyjson/releases/tag/v0.9
https://github.com/mailru/easyjson/releases/tag/v0.8

https://pkg.go.dev/github.com/mailru/easyjson?utm_source=godoc

<img width="396" alt="image" src="https://github.com/user-attachments/assets/a305ff37-ea52-496f-b156-4376ac2ab3d1" />

These versions aren't available.

```console
$ go install github.com/mailru/easyjson/easyjson@v0.9
go: github.com/mailru/easyjson/easyjson@v0.9: no matching versions for query "v0.9"
```

So how about releasing versions v0.8.0 and v0.9.0?

**Comment by rvasily** [comment]
done
