### ISSUE TITLE
undefined: net in net.IP

### ISSUE THREAD

**Issue by abh** [mailru/easyjson#46]
Building after running easyjson on the struct below fails with an error `undefined: net in net.IP` (because net doesn't get added to imports).

```
type S struct {
    Time       time.Time
    Client struct {
        IP   net.IP
        Mask uint8
    }
}
```

**Comment by narqo** [comment]
Hey @abh Could you check recent master? We've made some fixes related to `net.IP` handing in #106, which was merged recently.

**Comment by rvasily** [comment]
It must work fine now
