### ISSUE TITLE
Marshal methods are not generated for type aliases

### ISSUE THREAD

**Issue by oschwald** [mailru/easyjson#48]
Currently, it appears that type aliases are ignored when generating the marshaler methods. For instance,
on:

```
type Test struct {
    A string
}

type TestAlias Test
```

the file generated by `easyjson -all` does not contain any methods for `TestAlias` at all. This means that anything of type `TestAlias` is not an `easyjson.Marshaler` without an explicit cast.

**Comment by funny-falcon** [comment]
Go has no type aliases. `TestAlias` is a different type that has similar structure. Probably `easyjson` should generate methods for.

**Comment by ReenExe** [comment]
Fast solutions is add "preceding comment starts with easyjson:json"
```go
//easyjson:json
type TestAlias Test
```
it's work!
