### ISSUE TITLE
Give an explicit error message for nested maps with unsupported key type

### ISSUE THREAD

**Issue by hectorj** [mailru/easyjson#50]
When trying to apply easyjson to nested maps like `map[string]map[uint32]string`, it produces invalid code: 

```
        for v2_name, v2_value := range in.Field {
            if !v2_first {
                out.RawByte(',')
            }
            v2_first = false
            out.String(string(v2_name))
            out.RawByte(':')
        }
```

which gives this error:

> v2_value declared and not used

It would be nice to have an explicit error message, like we get with non-nested maps:

> map type uint32 not supported: only string keys are allowed

**Comment by cespare** [comment]
Related: #127

**Comment by rvasily** [comment]
PR #144 merged. Check it please
