### ISSUE TITLE
time.Time does not marshall correctly

### ISSUE THREAD

**Issue by chucknthem** [mailru/easyjson#52]
Marshalling and unmarshalling a struct like this leaves MyTime set to nil

type T struct {
   MyTime time.Time `json:"my_time"`
}

encoding/json supports this

**Comment by jnsone11** [comment]
You can simply change the type to "string" and set the variable from time.now().format... in the format you wish.

**Comment by zamotivator** [comment]
Why do not use https://tools.ietf.org/html/rfc3339 ?

**Comment by xStrom** [comment]
Are there still issues with `time.Time`? It seems to work just fine for me, but seeing this issue still open makes me a bit uneasy.

**Comment by rvasily** [comment]
Thre must be no issues with time now
