### ISSUE TITLE
EasyJSON disregards invalid input if a string prefix is valid

### ISSUE THREAD

**Issue by connor4312** [mailru/easyjson#72]
Discovered this quickly when throwing go-fuzz to detect behavioural differences between `encoding/json` and EasyJSON. EasyJSON seems to accept and stop parting if a prefix of a string is valid input. For example, all of the below lines are seen to be "valid" JSON strings:

```
null 4
{}{
null]
```

encoding/json returns an error when trying to parse these, EasyJSON accepts them

**Comment by vstarodub** [comment]
Thanks for the fix!
