### ISSUE TITLE
Invalid code generated for slices of struct pointers

### ISSUE THREAD

**Issue by hamaxx** [mailru/easyjson#8]
Easyjson adds unneeded and invalid package name to types when dealing with slices of struct pointers ([]*MyStruct).

Minimal example:

	package issue

	type S struct {
		B string
	}

	type Exp struct {
		A []*S
	}

Relevant generated code:

	func easyjson_decode_github_com_mailru_easyjson_issue_Exp(in *jlexer.Lexer, out *Exp) {
		in.Delim('{')
		for !in.IsDelim('}') {
			key := in.UnsafeString()
			in.WantColon()
			if in.IsNull() {
				in.Skip()
				in.WantComma()
				continue
			}
			switch key {
			case "A":
				in.Delim('[')
				if !in.IsDelim(']') {
					out.A = make([]*issue.S, 0, 8)
				} else {
					out.A = nil
				}
				for !in.IsDelim(']') {
					var v1 *issue.S
					if in.IsNull() {
						in.Skip()
						v1 = nil
					} else {
						v1 = new(S)
						(*v1).UnmarshalEasyJSON(in)
					}
					out.A = append(out.A, v1)
					in.WantComma()
				}
				in.Delim(']')
			default:
				in.SkipRecursive()
			}
			in.WantComma()
		}
		in.Delim('}')
	}

Invalid code (issue is not imported and can't be since it would produce import cycle):

    out.A = make([]*issue.S, 0, 8)

**Comment by vstarodub** [comment]
Thanks for a thorough report! This should be fixed now.
