### ISSUE TITLE
Wrong behaviour for embedded type

### ISSUE THREAD

**Issue by mappu** [mailru/easyjson#90]
Hi

```
type Parent struct {
  ParentMember string
  Child
}

type Child struct {
  ChildMember string
}
```

1. If Child has an easyjson implementation.
2. Then attempt to marshal Parent.
3. Then ParentMember is not present in output! (unexpected)

It's caused by parent inheriting child's implementation of json.Marhsaller interface.

I don't know if there's any possible solution. I hope there is. But maybe in README.MD should add a note saying "any type that embeds a type using easyjson must itself also use easyjson".

**Comment by pkaeding** [comment]
Another workaround (if you are unable to add easyjson to the `Parent`) is to not generate the standard marshaller for `Child` using easyjson: `-no_std_marshalers`.

Of course, that means you need to use the easyjson marshaller for your `Child`, and you don't get any performance benefit from easyjson when you are marshaling the `Parent`.

**Comment by GoWebProd** [comment]
Fixed
